language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE byob_frontend_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: UPU/9Z1CHRTjNn1RPe4R0zEQ/YKuULQGUfb0c4961GTX+80QQAH5/XsHMqDj1aXB4CEC++z3SVi/pzsnf3Y+UYNl6o77sikAt7KyQ9j2iZkhbNQSBA3ijkZS3E7262LPFEA6xEu8n3QAfdMIu9up5k0LxBbpBxg1vpN/r/7qqB59tfHr0pIoGJRmqc/RyJQDVIB9ffUNdVoLbA6+XHD1moOQlJt8F3af0tR5wlcfrmXchoIoKsAtso9W1/d01qzD0WUmGxOhJq98lXDVzcLMlpMifyjzaircJXA4rKastNFRmoLbug1K3QnDS0rrbyV+HGA0I+RhXZDAxaa/BFf+vlSaSF2rdxzqZEnuga9FbnEvE4oeMhYMTCKxWa+CjSCgqSrdv9YqhKfrMd/gNwJgvrWxLddncJVqNojKzbxHte4DI8qW12uixxqRd5RQQFbCnNR4oUV/tvUBHIf+z2Ft2EJiY3yhIDJybwLPaFMF/zXK2fS7pt2uywDYAQ8KKkoLwqEGgdQyFke1QUuucbg+OHwkzd9/kqpB01nnv5EAgcrBsylUdIonINT0IqalKbNvDrM4NWUfaDgV+nYSH83qL2UIEMD3nZDsXfJbBi+CFj1VheXYSV3+cyWd9PyJs/39IRqyqwnAaJU+TKVtrU2Pe3GJzXl6e+Gh30x+2aM9KOM=
  app: byob-frontend-ks-js
  skip_cleanup: true
